### ISSUE TITLE
plugins: [new SwupA11yPlugin()] written in example but "SwupA11YPlugin" is written in code

### ISSUE THREAD

**Issue by ckirby19** [swup/a11y-plugin#3] opened 2020-12-17 19:34 UTC
"SwupA11YPlugin" is writen with a capital Y in the code, but the example has a small y

const swup = new Swup({
  plugins: [new SwupA11yPlugin()]
});

should be:

const swup = new Swup({
  plugins: [new SwupA11YPlugin()]
});

or the code changed to have "SwupA11yPlugin"

**Comment by daun** [comment] 2020-12-17 20:09
Good catch, thanks for reporting.

Unfortunately, this is not a typo but a tooling issue. The correct name is `SwupA11yPlugin` with a lowercase `y` -- which would make the code example correct if you're using ES6 module imports. However, the plugin name seems to get mangled in minification, however, hence the incorrect spelling of the ES5 browser build export and filename. I'll need to take a look under the hood of the webpack boilerplate to see how to best solve this.

**Comment by ckirby19** [comment] 2020-12-17 21:56
Thanks for letting me know! I was using the Plugin directly by putting it into my lists of scripts, so I just changed it to 
`var SwupA11yPlugin = function (_Plugin) {
	_inherits(SwupA11yPlugin, _Plugin);

	function SwupA11yPlugin() {`  
etc with lowercase and I don't get any errors now, and I think it is working as I expect.

**Comment by gmrchk** [comment] 2021-03-13 20:56
The problem is [here](https://github.com/swup/a11y-plugin/blob/164d1000a56a2d7c60f78fa429038cd9d3dc981e/webpack.config.js#L7) I guess. Shall we just hardcode the correct name? It's there just so it works for plugins created from template out of the box, but this is kind of an exception.

**Comment by daun** [comment] 2021-03-14 23:41
@gmrchk I created a PR (#4) to address this issue. Unfortunately, it's a breaking change but we can just bump to `2.0`. Appreciate your review on the PR.

**Comment by daun** [comment] 2021-03-23 15:31
Resolved in #4.

**Closed by daun** 2021-03-23 15:31 UTC
